[server]
headless = true
address = "0.0.0.0"
port = 5000

[global]
developmentMode = false

[theme]
primaryColor = "#1E88E5"  # A nice blue color
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#1E1E1E"  # Slightly lighter dark
textColor = "#FAFAFA"  # Light text
font = "sans serif"